import {
  Megaphone,
  Package,
  ShoppingCart,
  Truck,
  Eye,
  Coins,
  Gift,
  Star,
  Hourglass,
  Camera,
  Bell,
  Disc3,
  Puzzle,
  BarChart3,
  Wrench,
  MessageCircle,
  Phone,
  Video,
  Smartphone,
  Shield,
  Layers,
  Target,
  Search,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const WIDGET_ICON_MAP: Record<string, LucideIcon> = {
  megaphone: Megaphone,
  package: Package,
  cart: ShoppingCart,
  truck: Truck,
  eye: Eye,
  coins: Coins,
  gift: Gift,
  star: Star,
  hourglass: Hourglass,
  camera: Camera,
  bell: Bell,
  wheel: Disc3,
  puzzle: Puzzle,
  'bar-chart': BarChart3,
  'message-circle': MessageCircle,
  phone: Phone,
  video: Video,
  smartphone: Smartphone,
  shield: Shield,
  layers: Layers,
  target: Target,
  search: Search,
  wrench: Wrench,
}
