<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Core\Models\Product;
use App\Enums\ProductAvailability;
use App\Enums\ProductStatus;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        Product::whereNotIn('slug', [
            'promo-line',
            'delivery-date',
            'sticky-buy-button',
            'trust-badges',
            'phone-mask',
            'minorder-goal',
            'cart-goal',
            'buyer-count',
            'stock-left',
            'photo-video-reviews',
            'recently-viewed',
            'video-preview',
            'floating-messengers',
            'cart-recommender',
            'prize-banner',
            'promo-auto-apply',
            'progressive-discount',
            'one-plus-one',
            'last-chance-popup',
            'spin-the-wheel',
            'sms-otp-checkout',
            'smart-search',
        ])->delete();

        $products = [
            [
                'slug' => 'promo-line',
                'name' => ['en' => 'Promo Ticker', 'uk' => 'Біжучий рядок'],
                'description' => [
                    'en' => 'Animated ticker with promotional text, discounts and special offers. Grabs attention so visitors never miss important news.',
                    'uk' => 'Анімований рядок з текстом акцій, знижок та спеціальних пропозицій. Привертає увагу та не дає пропустити важливе.',
                ],
                'icon' => 'megaphone',
                'tag_slug' => 'conversion',
                'is_popular' => true,
                'is_new' => false,
                'sort_order' => 0,
                'related_slugs' => ['sticky-buy-button', 'last-chance-popup', 'promo-auto-apply'],
                'config_schema' => [
                    'enabled' => ['type' => 'boolean', 'default' => true, 'label' => ['en' => 'Enabled', 'uk' => 'Увімкнено']],
                    'speed' => ['type' => 'number', 'default' => 80, 'label' => ['en' => 'Scroll speed (px/s)', 'uk' => 'Швидкість прокрутки (пкс/с)']],
                    'height' => ['type' => 'number', 'default' => 36, 'min' => 20, 'max' => 100, 'label' => ['en' => 'Height (px)', 'uk' => 'Висота (пкс)']],
                    'zIndex' => ['type' => 'number', 'default' => 999, 'label' => ['en' => 'Z-index', 'uk' => 'Z-індекс']],
                    'mode' => ['type' => 'select', 'options' => ['shift', 'overlay'], 'default' => 'shift', 'label' => ['en' => 'Display mode', 'uk' => 'Режим відображення']],
                    'ttlHours' => ['type' => 'number', 'default' => 24, 'min' => 1, 'max' => 168, 'label' => ['en' => 'Show once per N hours', 'uk' => 'Показувати раз на N годин']],
                    'isFixed' => ['type' => 'boolean', 'default' => true, 'label' => ['en' => 'Fixed position', 'uk' => 'Фіксована позиція']],
                    'mount' => [
                        'type' => 'group',
                        'label' => ['en' => 'Mount point', 'uk' => 'Точка монтування'],
                        'fields' => [
                            'selector' => ['type' => 'string', 'default' => '', 'label' => ['en' => 'CSS selector', 'uk' => 'CSS-селектор']],
                            'insert' => ['type' => 'select', 'options' => ['before', 'after'], 'default' => 'before', 'label' => ['en' => 'Insert position', 'uk' => 'Позиція вставки']],
                        ],
                    ],
                    'colors' => [
                        'type' => 'group',
                        'label' => ['en' => 'Colors', 'uk' => 'Кольори'],
                        'fields' => [
                            'desktop' => [
                                'type' => 'group',
                                'label' => ['en' => 'Desktop', 'uk' => 'Десктоп'],
                                'fields' => [
                                    'backgroundColor' => ['type' => 'color', 'default' => '#1e1b4b', 'label' => ['en' => 'Background', 'uk' => 'Фон']],
                                    'textColor' => ['type' => 'color', 'default' => '#e0e7ff', 'label' => ['en' => 'Text color', 'uk' => 'Колір тексту']],
                                ],
                            ],
                            'mobile' => [
                                'type' => 'group',
                                'label' => ['en' => 'Mobile', 'uk' => 'Мобільний'],
                                'fields' => [
                                    'backgroundColor' => ['type' => 'color', 'default' => '#1e1b4b', 'label' => ['en' => 'Background', 'uk' => 'Фон']],
                                    'textColor' => ['type' => 'color', 'default' => '#e0e7ff', 'label' => ['en' => 'Text color', 'uk' => 'Колір тексту']],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
            [
                'slug' => 'delivery-date',
                'name' => ['en' => 'Delivery Date', 'uk' => 'Дата доставки'],
                'description' => [
                    'en' => 'Shows the estimated delivery date directly on the product page. Removes uncertainty and builds buyer confidence.',
                    'uk' => 'Показує орієнтовну дату отримання замовлення прямо на сторінці товару. Знімає невизначеність у клієнта.',
                ],
                'icon' => 'package',
                'tag_slug' => 'trust',
                'is_popular' => true,
                'is_new' => false,
                'sort_order' => 1,
                'related_slugs' => ['trust-badges', 'phone-mask', 'sms-otp-checkout'],
                'config_schema' => [
                    'enabled' => ['type' => 'boolean', 'default' => true, 'label' => ['en' => 'Enabled', 'uk' => 'Увімкнено']],
                    'offsetDays' => ['type' => 'number', 'default' => 3, 'min' => 0, 'max' => 30, 'label' => ['en' => 'Delivery offset (days)', 'uk' => 'Зсув доставки (дні)']],
                    'selectors' => [
                        'type' => 'selectors',
                        'default' => [
                            [
                                'selector' => '#page > main > div > div.product__grid > div.product__column.product__column--right > div.product__block.product__block--orderBox.j-product-block > div > div.product-card.product-card--main > div',
                                'insert' => 'before',
                            ],
                            [
                                'selector' => '#main > div.wrapper > section > div > div.product__column.product__column--right.product__column--sticky > div > div:nth-child(1) > div > div:nth-child(5)',
                                'insert' => 'after',
                            ],
                        ],
                        'label' => ['en' => 'DOM selectors', 'uk' => 'DOM-селектори'],
                    ],
                ],
            ],
            [
                'slug' => 'sticky-buy-button',
                'name' => ['en' => 'Sticky Buy Button', 'uk' => 'Липка кнопка «Купити»'],
                'description' => [
                    'en' => 'Fixed "Buy" button pinned to the bottom of the screen on mobile. Customers can place an order at any moment without searching for the button.',
                    'uk' => 'Фіксована кнопка «Купити» знизу екрану на мобільних. Клієнт може оформити замовлення в будь-який момент, не шукаючи кнопку.',
                ],
                'icon' => 'layers',
                'tag_slug' => 'conversion',
                'is_popular' => true,
                'is_new' => false,
                'sort_order' => 2,
                'related_slugs' => ['promo-line', 'cart-goal', 'last-chance-popup'],
                'config_schema' => [
                    'enabled' => ['type' => 'boolean', 'default' => true, 'label' => ['en' => 'Enabled', 'uk' => 'Увімкнено']],
                    'buttonSelector' => ['type' => 'string', 'default' => '.j-buy-button-add', 'label' => ['en' => 'Original button CSS selector', 'uk' => 'CSS-селектор оригінальної кнопки']],
                    'mobileBreakpoint' => ['type' => 'number', 'default' => 768, 'min' => 320, 'max' => 1280, 'label' => ['en' => 'Mobile breakpoint (px)', 'uk' => 'Межа мобільного (пкс)']],
                    'backgroundColor' => ['type' => 'color', 'default' => '#5c1f2e', 'label' => ['en' => 'Button background', 'uk' => 'Фон кнопки']],
                    'textColor' => ['type' => 'color', 'default' => '#ffffff', 'label' => ['en' => 'Button text color', 'uk' => 'Колір тексту кнопки']],
                    'borderRadius' => ['type' => 'string', 'default' => '8px', 'label' => ['en' => 'Border radius', 'uk' => 'Радіус кутів']],
                    'zIndex' => ['type' => 'number', 'default' => 200, 'label' => ['en' => 'Z-index', 'uk' => 'Z-індекс']],
                    'bottomOffset' => ['type' => 'number', 'default' => 0, 'min' => 0, 'label' => ['en' => 'Bottom offset (px)', 'uk' => 'Відступ знизу (пкс)']],
                    'safeAreaPadding' => ['type' => 'boolean', 'default' => true, 'label' => ['en' => 'iOS safe area padding', 'uk' => 'Відступ iOS safe area']],
                ],
            ],
            [
                'slug' => 'trust-badges',
                'name' => ['en' => 'Trust Badges', 'uk' => 'Значки довіри'],
                'description' => [
                    'en' => 'Trust icons placed next to the "Buy" button: secure payment, returns, support. Eliminate hesitation before purchase.',
                    'uk' => 'Іконки гарантій поруч з кнопкою «Купити»: безпечна оплата, повернення, підтримка. Знімають сумніви перед покупкою.',
                ],
                'icon' => 'shield',
                'tag_slug' => 'trust',
                'is_popular' => false,
                'is_new' => false,
                'sort_order' => 3,
                'related_slugs' => ['delivery-date', 'phone-mask', 'buyer-count'],
                'config_schema' => null,
            ],
            [
                'slug' => 'phone-mask',
                'name' => ['en' => 'Phone Mask', 'uk' => 'Маска телефону'],
                'description' => [
                    'en' => 'Formats the phone input at checkout with country selector and flag. Reduces input errors and simplifies the ordering process.',
                    'uk' => 'Форматує поле вводу телефону на касі з вибором країни та прапорця. Зменшує помилки при введенні та спрощує оформлення замовлення.',
                ],
                'icon' => 'phone',
                'tag_slug' => 'trust',
                'is_popular' => false,
                'is_new' => false,
                'sort_order' => 4,
                'related_slugs' => ['trust-badges', 'delivery-date', 'sms-otp-checkout'],
                'config_schema' => null,
            ],
            [
                'slug' => 'minorder-goal',
                'name' => ['en' => 'Minimum Order Goal', 'uk' => 'Мінімальне замовлення'],
                'description' => [
                    'en' => 'A pop-up reminder about the minimum order amount. Warns customers in advance and reduces drop-offs at checkout.',
                    'uk' => 'Спливаюча плашка з нагадуванням про мінімальну суму замовлення. Попереджає клієнтів заздалегідь і зменшує відмови на касі.',
                ],
                'icon' => 'bar-chart',
                'tag_slug' => 'avg-order',
                'is_popular' => false,
                'is_new' => false,
                'sort_order' => 5,
                'related_slugs' => ['cart-goal', 'progressive-discount', 'one-plus-one'],
                'config_schema' => [
                    'enabled' => ['type' => 'boolean', 'default' => true, 'label' => ['en' => 'Enabled', 'uk' => 'Увімкнено']],
                    'threshold' => ['type' => 'number', 'default' => 500, 'min' => 0, 'label' => ['en' => 'Minimum order threshold (UAH)', 'uk' => 'Мінімальна сума замовлення (грн)']],
                    'background' => ['type' => 'color', 'default' => '#431407', 'label' => ['en' => 'Background', 'uk' => 'Фон']],
                    'achievedBackground' => ['type' => 'color', 'default' => '#14532d', 'label' => ['en' => 'Background (achieved)', 'uk' => 'Фон (досягнуто)']],
                    'textColor' => ['type' => 'color', 'default' => '#fed7aa', 'label' => ['en' => 'Text color', 'uk' => 'Колір тексту']],
                    'zIndex' => ['type' => 'number', 'default' => 999, 'label' => ['en' => 'Z-index', 'uk' => 'Z-індекс']],
                    'floatingWidget' => ['type' => 'boolean', 'default' => true, 'label' => ['en' => 'Floating widget', 'uk' => 'Плаваючий віджет']],
                    'shakeInterval' => ['type' => 'number', 'default' => 3000, 'min' => 0, 'label' => ['en' => 'Shake interval (ms)', 'uk' => 'Інтервал тряски (мс)']],
                    'desktopIconOnly' => ['type' => 'boolean', 'default' => true, 'label' => ['en' => 'Icon only on desktop', 'uk' => 'Тільки іконка на десктопі']],
                    'positionDesktop' => [
                        'type' => 'group',
                        'label' => ['en' => 'Position (desktop)', 'uk' => 'Позиція (десктоп)'],
                        'fields' => [
                            'left' => ['type' => 'number', 'default' => 16, 'label' => ['en' => 'Left (px)', 'uk' => 'Зліва (пкс)']],
                            'bottom' => ['type' => 'number', 'default' => 65, 'label' => ['en' => 'Bottom (px)', 'uk' => 'Знизу (пкс)']],
                        ],
                    ],
                    'positionMobile' => [
                        'type' => 'group',
                        'label' => ['en' => 'Position (mobile)', 'uk' => 'Позиція (мобільний)'],
                        'fields' => [
                            'left' => ['type' => 'number', 'default' => 16, 'label' => ['en' => 'Left (px)', 'uk' => 'Зліва (пкс)']],
                            'bottom' => ['type' => 'number', 'default' => 65, 'label' => ['en' => 'Bottom (px)', 'uk' => 'Знизу (пкс)']],
                        ],
                    ],
                ],
            ],
            [
                'slug' => 'cart-goal',
                'name' => ['en' => 'Cart Goal', 'uk' => 'Ціль кошика'],
                'description' => [
                    'en' => 'Progress bar showing how much more to spend for free shipping or a discount. Motivates customers to add items and increases average order value.',
                    'uk' => 'Прогрес-бар: покаже скільки залишилось до безкоштовної доставки або знижки. Мотивує додавати товари і збільшує середній чек.',
                ],
                'icon' => 'target',
                'tag_slug' => 'avg-order',
                'is_popular' => true,
                'is_new' => false,
                'sort_order' => 6,
                'related_slugs' => ['minorder-goal', 'progressive-discount', 'cart-recommender'],
                'config_schema' => [
                    'enabled' => ['type' => 'boolean', 'default' => true, 'label' => ['en' => 'Enabled', 'uk' => 'Увімкнено']],
                    'threshold' => ['type' => 'number', 'default' => 1000, 'min' => 0, 'label' => ['en' => 'Free shipping threshold (UAH)', 'uk' => 'Поріг безкоштовної доставки (грн)']],
                    'minimum' => ['type' => 'number', 'default' => 0, 'min' => 0, 'label' => ['en' => 'Minimum order amount (UAH)', 'uk' => 'Мінімальна сума замовлення (грн)']],
                    'floatingWidget' => ['type' => 'boolean', 'default' => true, 'label' => ['en' => 'Floating widget', 'uk' => 'Плаваючий віджет']],
                    'background' => ['type' => 'color', 'default' => '#172554', 'label' => ['en' => 'Background', 'uk' => 'Фон']],
                    'achievedBackground' => ['type' => 'color', 'default' => '#14532d', 'label' => ['en' => 'Background (achieved)', 'uk' => 'Фон (досягнуто)']],
                    'textColor' => ['type' => 'color', 'default' => '#bfdbfe', 'label' => ['en' => 'Text color', 'uk' => 'Колір тексту']],
                    'shakeInterval' => ['type' => 'number', 'default' => 3000, 'min' => 0, 'label' => ['en' => 'Shake interval (ms)', 'uk' => 'Інтервал тряски (мс)']],
                    'desktopIconOnly' => ['type' => 'boolean', 'default' => false, 'label' => ['en' => 'Icon only on desktop', 'uk' => 'Тільки іконка на десктопі']],
                    'zIndex' => ['type' => 'number', 'default' => 999, 'label' => ['en' => 'Z-index', 'uk' => 'Z-індекс']],
                    'positionDesktop' => [
                        'type' => 'group',
                        'label' => ['en' => 'Position (desktop)', 'uk' => 'Позиція (десктоп)'],
                        'fields' => [
                            'right' => ['type' => 'number', 'default' => 16, 'label' => ['en' => 'Right (px)', 'uk' => 'Справа (пкс)']],
                            'bottom' => ['type' => 'number', 'default' => 25, 'label' => ['en' => 'Bottom (px)', 'uk' => 'Знизу (пкс)']],
                        ],
                    ],
                    'positionMobile' => [
                        'type' => 'group',
                        'label' => ['en' => 'Position (mobile)', 'uk' => 'Позиція (мобільний)'],
                        'fields' => [
                            'left' => ['type' => 'number', 'default' => 16, 'label' => ['en' => 'Left (px)', 'uk' => 'Зліва (пкс)']],
                            'bottom' => ['type' => 'number', 'default' => 25, 'label' => ['en' => 'Bottom (px)', 'uk' => 'Знизу (пкс)']],
                        ],
                    ],
                ],
            ],
            [
                'slug' => 'buyer-count',
                'name' => ['en' => 'Buyer Count', 'uk' => 'Лічильник покупок'],
                'description' => [
                    'en' => 'Displays how many people have already bought this product. Social proof that encourages purchase and builds trust.',
                    'uk' => 'Відображає скільки людей вже купили цей товар. Соціальний доказ, що стимулює до покупки та підвищує довіру до товару.',
                ],
                'icon' => 'cart',
                'tag_slug' => 'social-proof',
                'is_popular' => true,
                'is_new' => false,
                'sort_order' => 7,
                'related_slugs' => ['photo-video-reviews', 'stock-left', 'recently-viewed'],
                'config_schema' => [
                    'enabled' => ['type' => 'boolean', 'default' => true, 'label' => ['en' => 'Enabled', 'uk' => 'Увімкнено']],
                    'selectors' => [
                        'type' => 'selectors',
                        'default' => [
                            [
                                'selector' => '#page > main > div > div.product__grid > div.product__column.product__column--right > div.product__block.product__block--orderBox.j-product-block > div > div.product-card.product-card--main > div.product-card__body > div.product-card__price-box',
                                'insert' => 'after',
                            ],
                        ],
                        'label' => ['en' => 'DOM selectors', 'uk' => 'DOM-селектори'],
                    ],
                    'minCount' => ['type' => 'number', 'default' => 8, 'min' => 1, 'max' => 999, 'label' => ['en' => 'Min count to show', 'uk' => 'Мін. кількість для показу']],
                    'maxCount' => ['type' => 'number', 'default' => 50, 'min' => 1, 'max' => 999, 'label' => ['en' => 'Max count to show', 'uk' => 'Макс. кількість для показу']],
                    'updateInterval' => ['type' => 'number', 'default' => 45, 'min' => 5, 'max' => 300, 'label' => ['en' => 'Update interval (sec)', 'uk' => 'Інтервал оновлення (сек)']],
                    'showForOutOfStock' => ['type' => 'boolean', 'default' => false, 'label' => ['en' => 'Show for out-of-stock', 'uk' => 'Показувати для товарів не в наявності']],
                    'backgroundColor' => ['type' => 'color', 'default' => '#4c1d95', 'label' => ['en' => 'Background', 'uk' => 'Фон']],
                    'textColor' => ['type' => 'color', 'default' => '#ede9fe', 'label' => ['en' => 'Text color', 'uk' => 'Колір тексту']],
                ],
            ],
            [
                'slug' => 'stock-left',
                'name' => ['en' => 'Stock Left', 'uk' => 'Залишок на складі'],
                'description' => [
                    'en' => 'Displays a dynamic stock count: "Only 5 left". Creates urgency and nudges customers toward a quick decision.',
                    'uk' => 'Показує динамічний залишок товару на складі: «Залишилось 5 шт». Створює відчуття терміновості та підштовхує до швидкого рішення.',
                ],
                'icon' => 'hourglass',
                'tag_slug' => 'urgency',
                'is_popular' => false,
                'is_new' => false,
                'sort_order' => 8,
                'related_slugs' => ['buyer-count', 'last-chance-popup', 'spin-the-wheel'],
                'config_schema' => null,
            ],
            [
                'slug' => 'photo-video-reviews',
                'name' => ['en' => 'Photo & Video Reviews', 'uk' => 'Фото-відео відгуки'],
                'description' => [
                    'en' => 'A block of real buyer photos under the product. Visual social proof that builds trust better than text reviews.',
                    'uk' => 'Блок з реальними фото від покупців під товаром. Візуальний соціальний доказ, що підвищує довіру краще за текстові відгуки.',
                ],
                'icon' => 'camera',
                'tag_slug' => 'social-proof',
                'is_popular' => false,
                'is_new' => true,
                'sort_order' => 9,
                'related_slugs' => ['buyer-count', 'recently-viewed', 'video-preview'],
                'config_schema' => null,
            ],
            [
                'slug' => 'recently-viewed',
                'name' => ['en' => 'Recently Viewed', 'uk' => 'Нещодавно переглянуті'],
                'description' => [
                    'en' => 'A horizontal strip of products the customer recently viewed. Brings forgotten items back into focus and increases browsing depth.',
                    'uk' => 'Горизонтальна стрічка з останніми товарами, які переглядав клієнт. Повертає увагу до забутих товарів і збільшує глибину перегляду.',
                ],
                'icon' => 'eye',
                'tag_slug' => 'engagement',
                'is_popular' => false,
                'is_new' => false,
                'sort_order' => 10,
                'related_slugs' => ['photo-video-reviews', 'floating-messengers', 'video-preview'],
                'config_schema' => null,
            ],
            [
                'slug' => 'video-preview',
                'name' => ['en' => 'Product Video Preview', 'uk' => 'Відео-превью товару'],
                'description' => [
                    'en' => 'A video thumbnail in the product gallery that plays on hover. Showcases the product in action without leaving for YouTube.',
                    'uk' => 'Відео-мініатюра в галереї товару при наведенні. Демонструє продукт у дії без переходу на YouTube.',
                ],
                'icon' => 'video',
                'tag_slug' => 'visual',
                'is_popular' => false,
                'is_new' => true,
                'sort_order' => 11,
                'related_slugs' => ['photo-video-reviews', 'recently-viewed', 'promo-line'],
                'config_schema' => [
                    'enabled' => ['type' => 'boolean', 'default' => true, 'label' => ['en' => 'Enabled', 'uk' => 'Увімкнено']],
                    'testVideoUrl' => ['type' => 'string', 'default' => 'https://lzrv.agency/pila.mp4', 'label' => ['en' => 'Test video URL', 'uk' => 'URL тестового відео']],
                    'mp4Selector' => ['type' => 'string', 'default' => 'a[href$=".mp4"]', 'label' => ['en' => 'MP4 link selector', 'uk' => 'Селектор MP4-посилання']],
                    'desktopSize' => ['type' => 'number', 'default' => 180, 'min' => 80, 'max' => 400, 'label' => ['en' => 'Desktop size (px)', 'uk' => 'Розмір на десктопі (пкс)']],
                    'mobileSize' => ['type' => 'number', 'default' => 160, 'min' => 60, 'max' => 300, 'label' => ['en' => 'Mobile size (px)', 'uk' => 'Розмір на мобільному (пкс)']],
                    'desktopMinimizedSize' => ['type' => 'number', 'default' => 140, 'min' => 60, 'max' => 300, 'label' => ['en' => 'Desktop minimized size (px)', 'uk' => 'Згорнутий розмір на десктопі (пкс)']],
                    'mobileMinimizedSize' => ['type' => 'number', 'default' => 120, 'min' => 40, 'max' => 200, 'label' => ['en' => 'Mobile minimized size (px)', 'uk' => 'Згорнутий розмір на мобільному (пкс)']],
                    'insetDesktop' => ['type' => 'number', 'default' => 30, 'min' => 0, 'label' => ['en' => 'Inset desktop (px)', 'uk' => 'Відступ на десктопі (пкс)']],
                    'insetMobile' => ['type' => 'number', 'default' => 15, 'min' => 0, 'label' => ['en' => 'Inset mobile (px)', 'uk' => 'Відступ на мобільному (пкс)']],
                    'borderColor' => ['type' => 'color', 'default' => '#7c3aed', 'label' => ['en' => 'Border color', 'uk' => 'Колір рамки']],
                    'observeSpa' => ['type' => 'boolean', 'default' => true, 'label' => ['en' => 'Observe SPA navigation', 'uk' => 'Відстежувати SPA-навігацію']],
                    'showOnMobile' => ['type' => 'boolean', 'default' => true, 'label' => ['en' => 'Show on mobile', 'uk' => 'Показувати на мобільному']],
                    'showOnDesktop' => ['type' => 'boolean', 'default' => true, 'label' => ['en' => 'Show on desktop', 'uk' => 'Показувати на десктопі']],
                ],
            ],
            [
                'slug' => 'floating-messengers',
                'name' => ['en' => 'Floating Messengers', 'uk' => 'Плаваючі месенджери'],
                'description' => [
                    'en' => 'WhatsApp, Telegram, Viber and phone buttons floating in the corner of the screen. Customers reach support in one tap.',
                    'uk' => 'Кнопки WhatsApp, Telegram, Viber та телефону, що плавають у куті екрану. Клієнт звертається до підтримки в один клік.',
                ],
                'icon' => 'message-circle',
                'tag_slug' => 'engagement',
                'is_popular' => false,
                'is_new' => false,
                'sort_order' => 12,
                'related_slugs' => ['recently-viewed', 'spin-the-wheel', 'buyer-count'],
                'config_schema' => null,
            ],
            [
                'slug' => 'cart-recommender',
                'name' => ['en' => 'AI Cart Recommendations', 'uk' => 'AI Рекомендації у кошику'],
                'description' => [
                    'en' => 'A carousel of related products shown directly inside the cart. Helps customers find what they forgot to add and increases order value.',
                    'uk' => 'Карусель супутніх товарів прямо в кошику. Допомагає клієнту знайти те, що він забув додати, та збільшує суму замовлення.',
                ],
                'icon' => 'puzzle',
                'tag_slug' => 'avg-order',
                'is_popular' => false,
                'is_new' => true,
                'sort_order' => 13,
                'related_slugs' => ['cart-goal', 'progressive-discount', 'one-plus-one'],
                'config_schema' => null,
            ],
            [
                'slug' => 'prize-banner',
                'name' => ['en' => 'Prize Banner', 'uk' => 'Банер з призом'],
                'description' => [
                    'en' => 'A banner showing a won promo code after a game (Spin the Wheel) or a last-chance popup. Reminds the customer to use the discount and complete the purchase.',
                    'uk' => 'Плашка з виграним промокодом після гри (Колесо фортуни) або попапу «останній шанс». Нагадує клієнту скористатись знижкою і завершити покупку.',
                ],
                'icon' => 'star',
                'tag_slug' => 'conversion',
                'is_popular' => false,
                'is_new' => false,
                'sort_order' => 14,
                'related_slugs' => ['spin-the-wheel', 'promo-auto-apply', 'last-chance-popup'],
                'config_schema' => null,
            ],
            [
                'slug' => 'promo-auto-apply',
                'name' => ['en' => 'Promo Auto-Apply', 'uk' => 'Авто-застосування промокоду'],
                'description' => [
                    'en' => 'Automatically inserts a promo code at checkout and shows a toast notification. Removes friction between winning a prize and completing the order.',
                    'uk' => 'Автоматично вставляє промокод у поле на касі та показує toast-сповіщення. Усуває тертя між виграним призом і оформленням замовлення.',
                ],
                'icon' => 'coins',
                'tag_slug' => 'conversion',
                'is_popular' => false,
                'is_new' => false,
                'sort_order' => 15,
                'related_slugs' => ['prize-banner', 'spin-the-wheel', 'promo-line'],
                'config_schema' => null,
            ],
            [
                'slug' => 'progressive-discount',
                'name' => ['en' => 'Progressive Discount', 'uk' => 'Прогресивна шкала знижок'],
                'description' => [
                    'en' => 'Visual scale: "2 items — 5%, 3 — 10%, 5 — 20%". Multiple motivation levels to increase the number of items in the order.',
                    'uk' => 'Візуальна шкала: «2 товари — 5%, 3 — 10%, 5 — 20%». Кілька рівнів мотивації для збільшення кількості товарів у замовленні.',
                ],
                'icon' => 'bar-chart',
                'tag_slug' => 'avg-order',
                'is_popular' => false,
                'is_new' => true,
                'sort_order' => 16,
                'related_slugs' => ['cart-goal', 'minorder-goal', 'one-plus-one'],
                'config_schema' => [
                    'enabled' => ['type' => 'boolean', 'default' => true, 'label' => ['en' => 'Enabled', 'uk' => 'Увімкнено']],
                    'tiers' => [
                        'type' => 'tiers',
                        'label' => ['en' => 'Discount tiers', 'uk' => 'Рівні знижки'],
                        'default' => [
                            ['minItems' => 2, 'percent' => 5,  'coupon' => 'CASH5'],
                            ['minItems' => 3, 'percent' => 10, 'coupon' => 'CASH10'],
                            ['minItems' => 5, 'percent' => 20, 'coupon' => 'CASH20'],
                        ],
                        'fields' => [
                            'minItems' => ['type' => 'number', 'default' => 2, 'min' => 1, 'label' => ['en' => 'Min items', 'uk' => 'Мін. товарів']],
                            'percent' => ['type' => 'number', 'default' => 5, 'min' => 0, 'label' => ['en' => 'Discount %', 'uk' => 'Знижка %']],
                            'coupon' => ['type' => 'string', 'default' => '', 'label' => ['en' => 'Coupon code', 'uk' => 'Код купона']],
                        ],
                    ],
                    'background' => ['type' => 'color', 'default' => '#0f172a', 'label' => ['en' => 'Background', 'uk' => 'Фон']],
                    'achievedBackground' => ['type' => 'color', 'default' => '#14532d', 'label' => ['en' => 'Background (top tier)', 'uk' => 'Фон (макс. рівень)']],
                    'textColor' => ['type' => 'color', 'default' => '#f8fafc', 'label' => ['en' => 'Text color', 'uk' => 'Колір тексту']],
                    'accentColor' => ['type' => 'color', 'default' => '#fbbf24', 'label' => ['en' => 'Accent color', 'uk' => 'Акцентний колір']],
                    'zIndex' => ['type' => 'number', 'default' => 50, 'label' => ['en' => 'Z-index', 'uk' => 'Z-індекс']],
                ],
            ],
            [
                'slug' => 'one-plus-one',
                'name' => ['en' => '1+1=3 Deal', 'uk' => 'Акція 1+1=3'],
                'description' => [
                    'en' => 'Buy two products — the cheapest one in the cart for 1 UAH. Motivates customers to add more items and increases average order value.',
                    'uk' => 'Купи два товари — найдешевший у кошику за 1 гривню. Мотивує додавати більше товарів та збільшує середній чек.',
                ],
                'icon' => 'gift',
                'tag_slug' => 'avg-order',
                'is_popular' => false,
                'is_new' => false,
                'sort_order' => 17,
                'related_slugs' => ['cart-goal', 'progressive-discount', 'cart-recommender'],
                'config_schema' => [
                    'enabled' => ['type' => 'boolean', 'default' => true, 'label' => ['en' => 'Enabled', 'uk' => 'Увімкнено']],
                    'apiUrl' => ['type' => 'string', 'default' => 'https://widgetality.com', 'label' => ['en' => 'API URL', 'uk' => 'URL API']],
                    'site' => ['type' => 'string', 'default' => '', 'label' => ['en' => 'Site domain', 'uk' => 'Домен сайту']],
                ],
            ],
            [
                'slug' => 'last-chance-popup',
                'name' => ['en' => 'Last Chance Popup', 'uk' => 'Попап «Останній шанс»'],
                'description' => [
                    'en' => 'A discount popup that gives the visitor one last chance — triggered when the cursor moves toward closing the tab. Recovers up to 15% of visitors who were about to leave.',
                    'uk' => 'Попап зі знижкою — останній шанс перед виходом: спрацьовує, коли клієнт рухає мишу до закриття вкладки. Повертає до 15% відвідувачів, що вже «йшли».',
                ],
                'icon' => 'bell',
                'tag_slug' => 'conversion',
                'is_popular' => false,
                'is_new' => true,
                'sort_order' => 18,
                'related_slugs' => ['spin-the-wheel', 'prize-banner', 'promo-auto-apply'],
                'config_schema' => null,
            ],
            [
                'slug' => 'spin-the-wheel',
                'name' => ['en' => 'Spin the Wheel', 'uk' => 'Колесо фортуни'],
                'description' => [
                    'en' => 'Gamified popup — spin the wheel and get a discount in exchange for an email. 5–20% conversion vs 1–3% for standard popups.',
                    'uk' => 'Гейміфікований попап — крути колесо, отримай знижку в обмін на email. Конверсія 5-20% проти 1-3% у звичайних попапів.',
                ],
                'icon' => 'wheel',
                'tag_slug' => 'engagement',
                'is_popular' => false,
                'is_new' => true,
                'sort_order' => 19,
                'related_slugs' => ['last-chance-popup', 'prize-banner', 'promo-auto-apply'],
                'config_schema' => null,
            ],
            [
                'slug' => 'sms-otp-checkout',
                'name' => ['en' => 'SMS OTP Checkout', 'uk' => 'SMS-верифікація в чекауті'],
                'description' => [
                    'en' => 'OTP phone verification at checkout for traffic from Google/Facebook. Filters fake orders and improves the quality of the customer base.',
                    'uk' => 'OTP-перевірка телефону в чекауті під час оформлення замовлення для трафіку з Google/Facebook. Відсіює фейкові замовлення та підвищує якість бази клієнтів.',
                ],
                'icon' => 'smartphone',
                'tag_slug' => 'trust',
                'is_popular' => false,
                'is_new' => true,
                'sort_order' => 20,
                'related_slugs' => ['delivery-date', 'trust-badges', 'phone-mask'],
                'config_schema' => null,
            ],
            [
                'slug' => 'smart-search',
                'name' => ['en' => 'Smart Search', 'uk' => 'Розумний пошук'],
                'description' => [
                    'en' => 'Site search with autocomplete, query history, typo correction and product previews',
                    'uk' => 'Розумний пошук по сайту з автодоповненням, історією запитів, корекцією помилок та прев\'ю товарів',
                ],
                'icon' => 'search',
                'tag_slug' => 'engagement',
                'status' => ProductStatus::Inactive->value,
                'is_popular' => false,
                'is_new' => true,
                'sort_order' => 22,
                'config_schema' => null,
                'related_slugs' => ['recently-viewed', 'cart-recommender', 'floating-messengers'],
            ],
        ];

        foreach ($products as $data) {
            Product::updateOrCreate(
                ['slug' => $data['slug']],
                array_merge([
                    'platform' => 'horoshop',
                    'status' => ProductStatus::Active->value,
                    'availability' => ProductAvailability::Available->value,
                    'is_popular' => false,
                    'is_new' => false,
                ], $data),
            );
        }
    }
}
