// Auto-extracted from old phone-mask.bundle.js — country dial codes, masks, examples, localized names.
// Names available in 4 languages: ukr (Ukrainian), rus (Russian), eng (English), pol (Polish).
// 'id' is the legacy Horoshop country ID — kept here only as opaque metadata; the widget does not use it.

export type CountryNames = {
  ukr: string;
  rus: string;
  eng: string;
  pol: string;
};

export type CountryEntry = {
  dial: string;
  masks: string[];
  example: string;
  names: CountryNames;
  id?: number | null;
};

export type Country = CountryEntry & { iso2: string; name: string };

export const COUNTRIES: Record<string, CountryEntry> = {
  UA: {
    dial: '+380',
    masks: ['(XX) XXX-XX-XX'],
    example: '(67) 123-45-67',
    names: { ukr: 'Україна', rus: 'Украина', eng: 'Ukraine', pol: 'Ukraina' },
    id: 182,
  },
  PL: {
    dial: '+48',
    masks: ['XXX XXX XXX'],
    example: '501 234 567',
    names: { ukr: 'Польща', rus: 'Польша', eng: 'Poland', pol: 'Polska' },
    id: 138,
  },
  RO: {
    dial: '+40',
    masks: ['XXX XXX XXX'],
    example: '712 345 678',
    names: { ukr: 'Румунія', rus: 'Румыния', eng: 'Romania', pol: 'Rumunia' },
    id: 141,
  },
  SK: {
    dial: '+421',
    masks: ['XXX XXX XXX'],
    example: '901 234 567',
    names: { ukr: 'Словаччина', rus: 'Словакия', eng: 'Slovakia', pol: 'Słowacja' },
    id: 156,
  },
  HU: {
    dial: '+36',
    masks: ['XX XXX XXXX'],
    example: '30 123 4567',
    names: { ukr: 'Угорщина', rus: 'Венгрия', eng: 'Hungary', pol: 'Węgry' },
    id: 74,
  },
  MD: {
    dial: '+373',
    masks: ['XXXX XXXX'],
    example: '6212 3456',
    names: { ukr: 'Молдова', rus: 'Молдова', eng: 'Moldova', pol: 'Mołdawia' },
    id: 115,
  },
  AT: {
    dial: '+43',
    masks: ['XXX XXX XXXX'],
    example: '650 123 4567',
    names: { ukr: 'Австрія', rus: 'Австрия', eng: 'Austria', pol: 'Austria' },
    id: 10,
  },
  BE: {
    dial: '+32',
    masks: ['XXX XX XX XX'],
    example: '470 12 34 56',
    names: { ukr: 'Бельгія', rus: 'Бельгия', eng: 'Belgium', pol: 'Belgia' },
    id: 17,
  },
  BG: {
    dial: '+359',
    masks: ['XXX XXX XXX'],
    example: '87 123 456',
    names: { ukr: 'Болгарія', rus: 'Болгария', eng: 'Bulgaria', pol: 'Bułgaria' },
    id: 26,
  },
  HR: {
    dial: '+385',
    masks: ['XXX XXX XXX'],
    example: '91 123 456',
    names: { ukr: 'Хорватія', rus: 'Хорватия', eng: 'Croatia', pol: 'Chorwacja' },
    id: 43,
  },
  CY: {
    dial: '+357',
    masks: ['XX XXX XXX'],
    example: '96 123 456',
    names: { ukr: 'Кіпр', rus: 'Кипр', eng: 'Cyprus', pol: 'Cypr' },
    id: null,
  },
  CZ: {
    dial: '+420',
    masks: ['XXX XXX XXX'],
    example: '601 123 456',
    names: { ukr: 'Чехія', rus: 'Чехия', eng: 'Czechia', pol: 'Czechy' },
    id: 46,
  },
  DK: {
    dial: '+45',
    masks: ['XX XX XX XX'],
    example: '20 12 34 56',
    names: { ukr: 'Данія', rus: 'Дания', eng: 'Denmark', pol: 'Dania' },
    id: 47,
  },
  EE: {
    dial: '+372',
    masks: ['XXXX XXXX'],
    example: '5123 4567',
    names: { ukr: 'Естонія', rus: 'Эстония', eng: 'Estonia', pol: 'Estonia' },
    id: 56,
  },
  FI: {
    dial: '+358',
    masks: ['XXX XXX XXXX'],
    example: '40 123 4567',
    names: { ukr: 'Фінляндія', rus: 'Финляндия', eng: 'Finland', pol: 'Finlandia' },
    id: 59,
  },
  FR: {
    dial: '+33',
    masks: ['X XX XX XX XX'],
    example: '6 12 34 56 78',
    names: { ukr: 'Франція', rus: 'Франция', eng: 'France', pol: 'Francja' },
    id: 60,
  },
  DE: {
    dial: '+49',
    masks: ['XXXX XXXXXXX', 'XXXX XXXXXXXX'],
    example: '1512 3456789',
    names: { ukr: 'Німеччина', rus: 'Германия', eng: 'Germany', pol: 'Niemcy' },
    id: 64,
  },
  GR: {
    dial: '+30',
    masks: ['XXX XXX XXXX'],
    example: '690 123 4567',
    names: { ukr: 'Греція', rus: 'Греция', eng: 'Greece', pol: 'Grecja' },
    id: 66,
  },
  IE: {
    dial: '+353',
    masks: ['XX XXX XXXX'],
    example: '85 123 4567',
    names: { ukr: 'Ірландія', rus: 'Ирландия', eng: 'Ireland', pol: 'Irlandia' },
    id: 80,
  },
  IT: {
    dial: '+39',
    masks: ['XXX XXX XXXX', 'XXX XXXX XXX'],
    example: '345 678 9012',
    names: { ukr: 'Італія', rus: 'Италия', eng: 'Italy', pol: 'Włochy' },
    id: 82,
  },
  LV: {
    dial: '+371',
    masks: ['XXXX XXXX'],
    example: '2123 4567',
    names: { ukr: 'Латвія', rus: 'Латвия', eng: 'Latvia', pol: 'Łotwa' },
    id: 94,
  },
  LT: {
    dial: '+370',
    masks: ['XXX XXXXX'],
    example: '612 34567',
    names: { ukr: 'Литва', rus: 'Литва', eng: 'Lithuania', pol: 'Litwa' },
    id: 100,
  },
  LU: {
    dial: '+352',
    masks: ['XXX XXX XXX'],
    example: '621 123 456',
    names: { ukr: 'Люксембург', rus: 'Люксембург', eng: 'Luxembourg', pol: 'Luksemburg' },
    id: 101,
  },
  MT: {
    dial: '+356',
    masks: ['XXXX XXXX'],
    example: '9696 1234',
    names: { ukr: 'Мальта', rus: 'Мальта', eng: 'Malta', pol: 'Malta' },
    id: 108,
  },
  NL: {
    dial: '+31',
    masks: ['XX XXX XXXX'],
    example: '6 123 4567',
    names: { ukr: 'Нідерланди', rus: 'Нидерланды', eng: 'Netherlands', pol: 'Holandia' },
    id: 124,
  },
  PT: {
    dial: '+351',
    masks: ['XXX XXX XXX'],
    example: '912 345 678',
    names: { ukr: 'Португалія', rus: 'Португалия', eng: 'Portugal', pol: 'Portugalia' },
    id: 139,
  },
  SI: {
    dial: '+386',
    masks: ['XXX XXX XXX'],
    example: '40 123 456',
    names: { ukr: 'Словенія', rus: 'Словения', eng: 'Slovenia', pol: 'Słowenia' },
    id: 157,
  },
  ES: {
    dial: '+34',
    masks: ['XXX XXX XXX'],
    example: '612 345 678',
    names: { ukr: 'Іспанія', rus: 'Испания', eng: 'Spain', pol: 'Hiszpania' },
    id: 162,
  },
  SE: {
    dial: '+46',
    masks: ['XX XXX XXXX', 'XX XXX XXXXX'],
    example: '70 123 4567',
    names: { ukr: 'Швеція', rus: 'Швеция', eng: 'Sweden', pol: 'Szwecja' },
    id: 167,
  },
  AL: {
    dial: '+355',
    masks: ['XXX XXX XXX'],
    example: '672 123 456',
    names: { ukr: 'Албанія', rus: 'Албания', eng: 'Albania', pol: 'Albania' },
    id: 2,
  },
  AD: {
    dial: '+376',
    masks: ['XXX XXX'],
    example: '312 345',
    names: { ukr: 'Андорра', rus: 'Андорра', eng: 'Andorra', pol: 'Andora' },
    id: 4,
  },
  BA: {
    dial: '+387',
    masks: ['XX XXX XXX'],
    example: '61 123 456',
    names: {
      ukr: 'Боснія і Герцеговина',
      rus: 'Босния и Герцеговина',
      eng: 'Bosnia and Herzegovina',
      pol: 'Bośnia i Hercegowina',
    },
    id: 22,
  },
  GI: {
    dial: '+350',
    masks: ['XXXXXX'],
    example: '200123',
    names: { ukr: 'Гібралтар', rus: 'Гибралтар', eng: 'Gibraltar', pol: 'Gibraltar' },
    id: 1031,
  },
  GL: {
    dial: '+299',
    masks: ['XX XX XX'],
    example: '22 12 34',
    names: { ukr: 'Гренландія', rus: 'Гренландия', eng: 'Greenland', pol: 'Grenlandia' },
    id: 1032,
  },
  IS: {
    dial: '+354',
    masks: ['XXX XXXX'],
    example: '611 1234',
    names: { ukr: 'Ісландія', rus: 'Исландия', eng: 'Iceland', pol: 'Islandia' },
    id: 75,
  },
  XK: {
    dial: '+383',
    masks: ['XXX XXX XXX'],
    example: '44 123 456',
    names: { ukr: 'Косово', rus: 'Косово', eng: 'Kosovo', pol: 'Kosowo' },
    id: null,
  },
  LI: {
    dial: '+423',
    masks: ['XXX XXX XXX'],
    example: '660 123 456',
    names: {
      ukr: 'Ліхтенштейн',
      rus: 'Лихтенштейн',
      eng: 'Liechtenstein',
      pol: 'Liechtenstein',
    },
    id: 99,
  },
  MC: {
    dial: '+377',
    masks: ['XX XX XX XX'],
    example: '06 12 34 56',
    names: { ukr: 'Монако', rus: 'Монако', eng: 'Monaco', pol: 'Monako' },
    id: 116,
  },
  ME: {
    dial: '+382',
    masks: ['XXX XXX XXX'],
    example: '67 123 456',
    names: { ukr: 'Чорногорія', rus: 'Черногория', eng: 'Montenegro', pol: 'Czarnogóra' },
    id: 118,
  },
  MK: {
    dial: '+389',
    masks: ['XXX XXX XXX'],
    example: '70 123 456',
    names: {
      ukr: 'Північна Македонія',
      rus: 'Северная Македония',
      eng: 'North Macedonia',
      pol: 'Macedonia Północna',
    },
    id: 102,
  },
  NO: {
    dial: '+47',
    masks: ['XXX XX XXX'],
    example: '412 34 567',
    names: { ukr: 'Норвегія', rus: 'Норвегия', eng: 'Norway', pol: 'Norwegia' },
    id: 129,
  },
  RU: {
    dial: '+7',
    masks: ['XXX XXX-XX-XX'],
    example: '912 345-67-89',
    names: { ukr: 'Росія', rus: 'Россия', eng: 'Russia', pol: 'Rosja' },
    id: 1036,
  },
  SM: {
    dial: '+378',
    masks: ['XXXX XXXX'],
    example: '0549 1234',
    names: { ukr: 'Сан-Марино', rus: 'Сан-Марино', eng: 'San Marino', pol: 'San Marino' },
    id: null,
  },
  RS: {
    dial: '+381',
    masks: ['XXX XXX XXXX'],
    example: '60 123 4567',
    names: { ukr: 'Сербія', rus: 'Сербия', eng: 'Serbia', pol: 'Serbia' },
    id: 152,
  },
  CH: {
    dial: '+41',
    masks: ['XXX XXX XXXX'],
    example: '76 123 45 67',
    names: { ukr: 'Швейцарія', rus: 'Швейцария', eng: 'Switzerland', pol: 'Szwajcaria' },
    id: 168,
  },
  GB: {
    dial: '+44',
    masks: ['XXXX XXXXXX', 'XXXX XXXXXXX'],
    example: '7123 456789',
    names: {
      ukr: 'Велика Британія',
      rus: 'Великобритания',
      eng: 'United Kingdom',
      pol: 'Wielka Brytania',
    },
    id: 184,
  },
  VA: {
    dial: '+3906698',
    masks: ['XXXX XXXX'],
    example: '06698 1234',
    names: { ukr: 'Ватикан', rus: 'Ватикан', eng: 'Vatican', pol: 'Watykan' },
    id: null,
  },
  AF: {
    dial: '+93',
    masks: ['XXX XXX XXXX'],
    example: '701 234 5678',
    names: { ukr: 'Афганістан', rus: 'Афганистан', eng: 'Afghanistan', pol: 'Afganistan' },
    id: 1,
  },
  AM: {
    dial: '+374',
    masks: ['XX XXX XXX'],
    example: '77 123 456',
    names: { ukr: 'Вірменія', rus: 'Армения', eng: 'Armenia', pol: 'Armenia' },
    id: 8,
  },
  AZ: {
    dial: '+994',
    masks: ['XX XXX XX XX'],
    example: '50 123 45 67',
    names: {
      ukr: 'Азербайджан',
      rus: 'Азербайджан',
      eng: 'Azerbaijan',
      pol: 'Azerbejdżan',
    },
    id: 11,
  },
  BH: {
    dial: '+973',
    masks: ['XXXX XXXX'],
    example: '3600 1234',
    names: { ukr: 'Бахрейн', rus: 'Бахрейн', eng: 'Bahrain', pol: 'Bahrajn' },
    id: null,
  },
  BD: {
    dial: '+880',
    masks: ['XXXX XXX XXX'],
    example: '1700 123 456',
    names: { ukr: 'Бангладеш', rus: 'Бангладеш', eng: 'Bangladesh', pol: 'Bangladesz' },
    id: 14,
  },
  BT: {
    dial: '+975',
    masks: ['X XXX XXX'],
    example: '1 710 123',
    names: { ukr: 'Бутан', rus: 'Бутан', eng: 'Bhutan', pol: 'Bhutan' },
    id: 1044,
  },
  BN: {
    dial: '+673',
    masks: ['XXX XXXX'],
    example: '712 3456',
    names: { ukr: 'Бруней', rus: 'Бруней', eng: 'Brunei', pol: 'Brunei' },
    id: 1045,
  },
  KH: {
    dial: '+855',
    masks: ['XX XXX XXX'],
    example: '12 345 678',
    names: { ukr: 'Камбоджа', rus: 'Камбоджа', eng: 'Cambodia', pol: 'Kambodża' },
    id: 29,
  },
  CN: {
    dial: '+86',
    masks: ['XXX XXXX XXXX'],
    example: '130 1234 5678',
    names: { ukr: 'Китай', rus: 'Китай', eng: 'China', pol: 'Chiny' },
    id: 1047,
  },
  GE: {
    dial: '+995',
    masks: ['XXX XX XX XX'],
    example: '555 12 34 56',
    names: { ukr: 'Грузія', rus: 'Грузия', eng: 'Georgia', pol: 'Gruzja' },
    id: 63,
  },
  HK: {
    dial: '+852',
    masks: ['XXXX XXXX'],
    example: '5123 4567',
    names: { ukr: 'Гонконг', rus: 'Гонконг', eng: 'Hong Kong', pol: 'Hongkong' },
    id: 1049,
  },
  IN: {
    dial: '+91',
    masks: ['XXXXX XXXXX'],
    example: '98765 43210',
    names: { ukr: 'Індія', rus: 'Индия', eng: 'India', pol: 'Indie' },
    id: 76,
  },
  ID: {
    dial: '+62',
    masks: ['XXXX XXXX XXX'],
    example: '8123 456 789',
    names: { ukr: 'Індонезія', rus: 'Индонезия', eng: 'Indonesia', pol: 'Indonezja' },
    id: 77,
  },
  IR: {
    dial: '+98',
    masks: ['XXX XXX XXXX'],
    example: '912 345 6789',
    names: { ukr: 'Іран', rus: 'Иран', eng: 'Iran', pol: 'Iran' },
    id: 1052,
  },
  IQ: {
    dial: '+964',
    masks: ['XXX XXX XXXX'],
    example: '750 123 4567',
    names: { ukr: 'Ірак', rus: 'Ирак', eng: 'Iraq', pol: 'Irak' },
    id: 79,
  },
  IL: {
    dial: '+972',
    masks: ['XX XXX XXXX'],
    example: '50 123 4567',
    names: { ukr: 'Ізраїль', rus: 'Израиль', eng: 'Israel', pol: 'Izrael' },
    id: 1054,
  },
  JO: {
    dial: '+962',
    masks: ['XX XXXX XXX'],
    example: '77 1234 567',
    names: { ukr: 'Йорданія', rus: 'Иордания', eng: 'Jordan', pol: 'Jordania' },
    id: 85,
  },
  JP: {
    dial: '+81',
    masks: ['XX XXXX XXXX'],
    example: '90 1234 5678',
    names: { ukr: 'Японія', rus: 'Япония', eng: 'Japan', pol: 'Japonia' },
    id: 84,
  },
  KZ: {
    dial: '+76',
    masks: ['XXX XXX XX XX'],
    example: '777 123 45 67',
    names: { ukr: 'Казахстан', rus: 'Казахстан', eng: 'Kazakhstan', pol: 'Kazachstan' },
    id: 86,
  },
  KW: {
    dial: '+965',
    masks: ['XXXX XXXX'],
    example: '5000 1234',
    names: { ukr: 'Кувейт', rus: 'Кувейт', eng: 'Kuwait', pol: 'Kuwejt' },
    id: 1058,
  },
  KG: {
    dial: '+996',
    masks: ['XXX XX XX XX'],
    example: '555 12 34 56',
    names: { ukr: 'Киргизстан', rus: 'Киргизия', eng: 'Kyrgyzstan', pol: 'Kirgistan' },
    id: 92,
  },
  LA: {
    dial: '+856',
    masks: ['XXXX XXX XXX'],
    example: '2023 456 789',
    names: { ukr: 'Лаос', rus: 'Лаос', eng: 'Laos', pol: 'Laos' },
    id: 1060,
  },
  LB: {
    dial: '+961',
    masks: ['XX XXX XXX'],
    example: '71 123 456',
    names: { ukr: 'Ліван', rus: 'Ливан', eng: 'Lebanon', pol: 'Liban' },
    id: 1061,
  },
  MY: {
    dial: '+60',
    masks: ['XX XXX XXXX'],
    example: '12 345 6789',
    names: { ukr: 'Малайзія', rus: 'Малайзия', eng: 'Malaysia', pol: 'Malezja' },
    id: 105,
  },
  MV: {
    dial: '+960',
    masks: ['XXX XXXX'],
    example: '771 2345',
    names: { ukr: 'Мальдіви', rus: 'Мальдивы', eng: 'Maldives', pol: 'Malediwy' },
    id: 1063,
  },
  MN: {
    dial: '+976',
    masks: ['XXXX XXXX'],
    example: '8812 3456',
    names: { ukr: 'Монголія', rus: 'Монголия', eng: 'Mongolia', pol: 'Mongolia' },
    id: 117,
  },
  MM: {
    dial: '+95',
    masks: ['XXXX XXX'],
    example: '9123 456',
    names: { ukr: "М'янма", rus: 'Мьянма', eng: 'Myanmar', pol: 'Mjanma' },
    id: 1065,
  },
  NP: {
    dial: '+977',
    masks: ['XXX XXX XXXX'],
    example: '984 123 4567',
    names: { ukr: 'Непал', rus: 'Непал', eng: 'Nepal', pol: 'Nepal' },
    id: 1066,
  },
  KP: {
    dial: '+850',
    masks: ['XXXX XXXX'],
    example: '191 1234',
    names: {
      ukr: 'Північна Корея',
      rus: 'Северная Корея',
      eng: 'North Korea',
      pol: 'Korea Północna',
    },
    id: 1067,
  },
  OM: {
    dial: '+968',
    masks: ['XXXX XXXX'],
    example: '9123 4567',
    names: { ukr: 'Оман', rus: 'Оман', eng: 'Oman', pol: 'Oman' },
    id: 1068,
  },
  PK: {
    dial: '+92',
    masks: ['XXX XXX XXXX'],
    example: '300 123 4567',
    names: { ukr: 'Пакистан', rus: 'Пакистан', eng: 'Pakistan', pol: 'Pakistan' },
    id: 131,
  },
  PS: {
    dial: '+970',
    masks: ['XXX XXX XXX'],
    example: '599 123 456',
    names: { ukr: 'Палестина', rus: 'Палестина', eng: 'Palestine', pol: 'Palestyna' },
    id: 1070,
  },
  PH: {
    dial: '+63',
    masks: ['XXXX XXX XXXX'],
    example: '917 123 4567',
    names: { ukr: 'Філіппіни', rus: 'Филиппины', eng: 'Philippines', pol: 'Filipiny' },
    id: 1071,
  },
  QA: {
    dial: '+974',
    masks: ['XXXX XXXX'],
    example: '3300 1234',
    names: { ukr: 'Катар', rus: 'Катар', eng: 'Qatar', pol: 'Katar' },
    id: 140,
  },
  SA: {
    dial: '+966',
    masks: ['XX XXX XXXX'],
    example: '50 123 4567',
    names: {
      ukr: 'Саудівська Аравія',
      rus: 'Саудовская Аравия',
      eng: 'Saudi Arabia',
      pol: 'Arabia Saudyjska',
    },
    id: 150,
  },
  SG: {
    dial: '+65',
    masks: ['XXXX XXXX'],
    example: '8123 4567',
    names: { ukr: 'Сінгапур', rus: 'Сингапур', eng: 'Singapore', pol: 'Singapur' },
    id: 1074,
  },
  KR: {
    dial: '+82',
    masks: ['XX XXXX XXXX'],
    example: '10 1234 5678',
    names: {
      ukr: 'Південна Корея',
      rus: 'Южная Корея',
      eng: 'South Korea',
      pol: 'Korea Południowa',
    },
    id: 1075,
  },
  LK: {
    dial: '+94',
    masks: ['XX XXX XXXX'],
    example: '71 123 4567',
    names: { ukr: 'Шрі-Ланка', rus: 'Шри-Ланка', eng: 'Sri Lanka', pol: 'Sri Lanka' },
    id: 1076,
  },
  SY: {
    dial: '+963',
    masks: ['XXX XXX XXX'],
    example: '944 123 456',
    names: { ukr: 'Сирія', rus: 'Сирия', eng: 'Syria', pol: 'Syria' },
    id: 169,
  },
  TW: {
    dial: '+886',
    masks: ['XXXX XXX XXX'],
    example: '9123 456 789',
    names: { ukr: 'Тайвань', rus: 'Тайвань', eng: 'Taiwan', pol: 'Tajwan' },
    id: 194,
  },
  TJ: {
    dial: '+992',
    masks: ['XXX XX XX XX'],
    example: '917 12 34 56',
    names: {
      ukr: 'Таджикистан',
      rus: 'Таджикистан',
      eng: 'Tajikistan',
      pol: 'Tadżykistan',
    },
    id: 170,
  },
  TH: {
    dial: '+66',
    masks: ['XX XXX XXXX'],
    example: '81 234 5678',
    names: { ukr: 'Таїланд', rus: 'Таиланд', eng: 'Thailand', pol: 'Tajlandia' },
    id: 172,
  },
  TL: {
    dial: '+670',
    masks: ['XXX XXXX'],
    example: '772 1234',
    names: {
      ukr: 'Східний Тимор',
      rus: 'Восточный Тимор',
      eng: 'Timor-Leste',
      pol: 'Timor Wschodni',
    },
    id: 1081,
  },
  TR: {
    dial: '+90',
    masks: ['XXX XXX XX XX'],
    example: '532 123 45 67',
    names: { ukr: 'Туреччина', rus: 'Турция', eng: 'Turkey', pol: 'Turcja' },
    id: 178,
  },
  TM: {
    dial: '+993',
    masks: ['XX XX XX XX'],
    example: '65 12 34 56',
    names: {
      ukr: 'Туркменістан',
      rus: 'Туркменистан',
      eng: 'Turkmenistan',
      pol: 'Turkmenistan',
    },
    id: 179,
  },
  AE: {
    dial: '+971',
    masks: ['XX XXX XXXX'],
    example: '50 123 4567',
    names: {
      ukr: "Об'єднані Арабські Емірати",
      rus: 'ОАЭ',
      eng: 'United Arab Emirates',
      pol: 'Zjednoczone Emiraty Arabskie',
    },
    id: 1084,
  },
  UZ: {
    dial: '+998',
    masks: ['XX XXX XX XX'],
    example: '90 123 45 67',
    names: { ukr: 'Узбекистан', rus: 'Узбекистан', eng: 'Uzbekistan', pol: 'Uzbekistan' },
    id: 187,
  },
  VN: {
    dial: '+84',
    masks: ['XXX XXX XX XX'],
    example: '90 123 45 67',
    names: { ukr: "В'єтнам", rus: 'Вьетнам', eng: 'Vietnam', pol: 'Wietnam' },
    id: 1086,
  },
  YE: {
    dial: '+967',
    masks: ['XXX XXX XXX'],
    example: '712 345 678',
    names: { ukr: 'Ємен', rus: 'Йемен', eng: 'Yemen', pol: 'Jemen' },
    id: 1087,
  },
  DZ: {
    dial: '+213',
    masks: ['XXX XX XX XX'],
    example: '555 12 34 56',
    names: { ukr: 'Алжир', rus: 'Алжир', eng: 'Algeria', pol: 'Algieria' },
  },
  AO: {
    dial: '+244',
    masks: ['XXX XXX XXX'],
    example: '923 456 789',
    names: { ukr: 'Ангола', rus: 'Ангола', eng: 'Angola', pol: 'Angola' },
  },
  BJ: {
    dial: '+229',
    masks: ['XX XX XX XX'],
    example: '90 12 34 56',
    names: { ukr: 'Бенін', rus: 'Бенин', eng: 'Benin', pol: 'Benin' },
  },
  BW: {
    dial: '+267',
    masks: ['XX XXX XXX'],
    example: '71 123 456',
    names: { ukr: 'Ботсвана', rus: 'Ботсвана', eng: 'Botswana', pol: 'Botswana' },
  },
  BF: {
    dial: '+226',
    masks: ['XX XX XX XX'],
    example: '70 12 34 56',
    names: {
      ukr: 'Буркіна-Фасо',
      rus: 'Буркина-Фасо',
      eng: 'Burkina Faso',
      pol: 'Burkina Faso',
    },
  },
  BI: {
    dial: '+257',
    masks: ['XX XX XX XX'],
    example: '79 12 34 56',
    names: { ukr: 'Бурунді', rus: 'Бурунди', eng: 'Burundi', pol: 'Burundi' },
  },
  CM: {
    dial: '+237',
    masks: ['XXXX XXXX'],
    example: '6901 2345',
    names: { ukr: 'Камерун', rus: 'Камерун', eng: 'Cameroon', pol: 'Kamerun' },
  },
  CV: {
    dial: '+238',
    masks: ['XXX XX XX'],
    example: '991 12 34',
    names: {
      ukr: 'Кабо-Верде',
      rus: 'Кабо-Верде',
      eng: 'Cape Verde',
      pol: 'Wyspy Zielonego Przylądka',
    },
  },
  CF: {
    dial: '+236',
    masks: ['XX XX XX XX'],
    example: '70 12 34 56',
    names: {
      ukr: 'Центральноафриканська Республіка',
      rus: 'ЦАР',
      eng: 'Central African Republic',
      pol: 'Republika Środkowoafrykańska',
    },
  },
  TD: {
    dial: '+235',
    masks: ['XX XX XX XX'],
    example: '63 12 34 56',
    names: { ukr: 'Чад', rus: 'Чад', eng: 'Chad', pol: 'Czad' },
  },
  KM: {
    dial: '+269',
    masks: ['XXX XX XX'],
    example: '321 12 34',
    names: { ukr: 'Комори', rus: 'Коморы', eng: 'Comoros', pol: 'Komory' },
  },
  CG: {
    dial: '+242',
    masks: ['XX XXX XXXX'],
    example: '06 123 4567',
    names: { ukr: 'Конго', rus: 'Конго', eng: 'Congo', pol: 'Kongo' },
  },
  CD: {
    dial: '+243',
    masks: ['XXX XXX XXX'],
    example: '899 123 456',
    names: {
      ukr: 'Демократична Республіка Конго',
      rus: 'ДР Конго',
      eng: 'Congo (DRC)',
      pol: 'Demokratyczna Republika Konga',
    },
  },
  CI: {
    dial: '+225',
    masks: ['XX XX XX XX'],
    example: '01 12 34 56',
    names: {
      ukr: "Кот-д'Івуар",
      rus: "Кот-д'Ивуар",
      eng: "Côte d'Ivoire",
      pol: 'Wybrzeże Kości Słoniowej',
    },
  },
  DJ: {
    dial: '+253',
    masks: ['XX XX XX XX'],
    example: '77 12 34 56',
    names: { ukr: 'Джибуті', rus: 'Джибути', eng: 'Djibouti', pol: 'Dżibuti' },
  },
  EG: {
    dial: '+20',
    masks: ['XXX XXX XXXX'],
    example: '100 123 4567',
    names: { ukr: 'Єгипет', rus: 'Египет', eng: 'Egypt', pol: 'Egipt' },
  },
  GQ: {
    dial: '+240',
    masks: ['XXX XXX XXX'],
    example: '222 123 456',
    names: {
      ukr: 'Екваторіальна Гвінея',
      rus: 'Экваториальная Гвинея',
      eng: 'Equatorial Guinea',
      pol: 'Gwinea Równikowa',
    },
  },
  ER: {
    dial: '+291',
    masks: ['X XXX XXX'],
    example: '1 123 456',
    names: { ukr: 'Еритрея', rus: 'Эритрея', eng: 'Eritrea', pol: 'Erytrea' },
  },
  ET: {
    dial: '+251',
    masks: ['XXX XXX XXXX'],
    example: '911 123 4567',
    names: { ukr: 'Ефіопія', rus: 'Эфиопия', eng: 'Ethiopia', pol: 'Etiopia' },
  },
  GA: {
    dial: '+241',
    masks: ['XX XX XX XX'],
    example: '06 12 34 56',
    names: { ukr: 'Габон', rus: 'Габон', eng: 'Gabon', pol: 'Gabon' },
  },
  GM: {
    dial: '+220',
    masks: ['XXX XXXX'],
    example: '301 2345',
    names: { ukr: 'Гамбія', rus: 'Гамбия', eng: 'Gambia', pol: 'Gambia' },
  },
  GH: {
    dial: '+233',
    masks: ['XXX XXX XXX'],
    example: '24 123 456',
    names: { ukr: 'Гана', rus: 'Гана', eng: 'Ghana', pol: 'Ghana' },
  },
  GN: {
    dial: '+224',
    masks: ['XXX XX XX XX'],
    example: '621 12 34 56',
    names: { ukr: 'Гвінея', rus: 'Гвинея', eng: 'Guinea', pol: 'Gwinea' },
  },
  GW: {
    dial: '+245',
    masks: ['XXX XXXX'],
    example: '955 1234',
    names: {
      ukr: 'Гвінея-Бісау',
      rus: 'Гвинея-Бисау',
      eng: 'Guinea-Bissau',
      pol: 'Gwinea Bissau',
    },
  },
  KE: {
    dial: '+254',
    masks: ['XXX XXX XXX'],
    example: '712 345 678',
    names: { ukr: 'Кенія', rus: 'Кения', eng: 'Kenya', pol: 'Kenia' },
  },
  LS: {
    dial: '+266',
    masks: ['XXX XXXX'],
    example: '5012 3456',
    names: { ukr: 'Лесото', rus: 'Лесото', eng: 'Lesotho', pol: 'Lesotho' },
  },
  LR: {
    dial: '+231',
    masks: ['XX XXX XXX'],
    example: '77 123 456',
    names: { ukr: 'Ліберія', rus: 'Либерия', eng: 'Liberia', pol: 'Liberia' },
  },
  LY: {
    dial: '+218',
    masks: ['XX XXX XXXX'],
    example: '91 123 4567',
    names: { ukr: 'Лівія', rus: 'Ливия', eng: 'Libya', pol: 'Libia' },
  },
  MG: {
    dial: '+261',
    masks: ['XX XX XXX XX'],
    example: '32 12 345 67',
    names: { ukr: 'Мадагаскар', rus: 'Мадагаскар', eng: 'Madagascar', pol: 'Madagaskar' },
  },
  MW: {
    dial: '+265',
    masks: ['XXX XX XX XX'],
    example: '991 12 34 56',
    names: { ukr: 'Малаві', rus: 'Малави', eng: 'Malawi', pol: 'Malawi' },
  },
  ML: {
    dial: '+223',
    masks: ['XX XX XX XX'],
    example: '70 12 34 56',
    names: { ukr: 'Малі', rus: 'Мали', eng: 'Mali', pol: 'Mali' },
  },
  MR: {
    dial: '+222',
    masks: ['XXX XX XX XX'],
    example: '222 12 34 56',
    names: { ukr: 'Мавританія', rus: 'Мавритания', eng: 'Mauritania', pol: 'Mauretania' },
  },
  MU: {
    dial: '+230',
    masks: ['XXX XXXX'],
    example: '525 1234',
    names: { ukr: 'Маврикій', rus: 'Маврикий', eng: 'Mauritius', pol: 'Mauritius' },
  },
  MA: {
    dial: '+212',
    masks: ['XXX XXX XXX'],
    example: '612 345 678',
    names: { ukr: 'Марокко', rus: 'Марокко', eng: 'Morocco', pol: 'Maroko' },
  },
  MZ: {
    dial: '+258',
    masks: ['XX XXX XXXX'],
    example: '82 123 4567',
    names: { ukr: 'Мозамбік', rus: 'Мозамбик', eng: 'Mozambique', pol: 'Mozambik' },
  },
  NA: {
    dial: '+264',
    masks: ['XX XXX XXXX'],
    example: '81 123 4567',
    names: { ukr: 'Намібія', rus: 'Намибия', eng: 'Namibia', pol: 'Namibia' },
  },
  NE: {
    dial: '+227',
    masks: ['XX XX XX XX'],
    example: '90 12 34 56',
    names: { ukr: 'Нігер', rus: 'Нигер', eng: 'Niger', pol: 'Niger' },
  },
  NG: {
    dial: '+234',
    masks: ['XXX XXX XXXX'],
    example: '803 123 4567',
    names: { ukr: 'Нігерія', rus: 'Нигерия', eng: 'Nigeria', pol: 'Nigeria' },
  },
  RW: {
    dial: '+250',
    masks: ['XXX XXX XXX'],
    example: '788 123 456',
    names: { ukr: 'Руанда', rus: 'Руанда', eng: 'Rwanda', pol: 'Rwanda' },
  },
  SH: {
    dial: '+290',
    masks: ['XXXXX'],
    example: '12345',
    names: {
      ukr: 'Острів Святої Єлени',
      rus: 'Остров Святой Елены',
      eng: 'Saint Helena',
      pol: 'Wyspa Świętej Heleny',
    },
  },
  ST: {
    dial: '+239',
    masks: ['XX XXX XX'],
    example: '98 123 45',
    names: {
      ukr: 'Сан-Томе і Принсіпі',
      rus: 'Сан-Томе и Принсипи',
      eng: 'São Tomé and Príncipe',
      pol: 'Wyspy Świętego Tomasza i Książęca',
    },
  },
  SN: {
    dial: '+221',
    masks: ['XX XXX XXXX'],
    example: '70 123 4567',
    names: { ukr: 'Сенегал', rus: 'Сенегал', eng: 'Senegal', pol: 'Senegal' },
  },
  SC: {
    dial: '+248',
    masks: ['X XXX XXX'],
    example: '2 510 123',
    names: {
      ukr: 'Сейшельські Острови',
      rus: 'Сейшелы',
      eng: 'Seychelles',
      pol: 'Seszele',
    },
  },
  SL: {
    dial: '+232',
    masks: ['XX XXX XXX'],
    example: '25 123 456',
    names: {
      ukr: 'Сьєрра-Леоне',
      rus: 'Сьерра-Леоне',
      eng: 'Sierra Leone',
      pol: 'Sierra Leone',
    },
  },
  SO: {
    dial: '+252',
    masks: ['XX XXX XXX'],
    example: '61 123 456',
    names: { ukr: 'Сомалі', rus: 'Сомали', eng: 'Somalia', pol: 'Somalia' },
  },
  ZA: {
    dial: '+27',
    masks: ['XX XXX XXXX'],
    example: '71 123 4567',
    names: {
      ukr: 'Південно-Африканська Республіка',
      rus: 'ЮАР',
      eng: 'South Africa',
      pol: 'Republika Południowej Afryki',
    },
  },
  SS: {
    dial: '+211',
    masks: ['XXX XXX XXX'],
    example: '977 123 456',
    names: {
      ukr: 'Південний Судан',
      rus: 'Южный Судан',
      eng: 'South Sudan',
      pol: 'Sudan Południowy',
    },
  },
  SD: {
    dial: '+249',
    masks: ['XXX XXX XXX'],
    example: '91 123 456',
    names: { ukr: 'Судан', rus: 'Судан', eng: 'Sudan', pol: 'Sudan' },
  },
  SZ: {
    dial: '+268',
    masks: ['XX XX XX XX'],
    example: '76 12 34 56',
    names: { ukr: 'Есватіні', rus: 'Эсватини', eng: 'Eswatini', pol: 'Eswatini' },
  },
  TZ: {
    dial: '+255',
    masks: ['XXX XXX XXX'],
    example: '621 123 456',
    names: { ukr: 'Танзанія', rus: 'Танзания', eng: 'Tanzania', pol: 'Tanzania' },
  },
  TG: {
    dial: '+228',
    masks: ['XX XX XX XX'],
    example: '90 12 34 56',
    names: { ukr: 'Того', rus: 'Того', eng: 'Togo', pol: 'Togo' },
  },
  TN: {
    dial: '+216',
    masks: ['XX XXX XXX'],
    example: '20 123 456',
    names: { ukr: 'Туніс', rus: 'Тунис', eng: 'Tunisia', pol: 'Tunezja' },
  },
  UG: {
    dial: '+256',
    masks: ['XXX XXX XXX'],
    example: '701 123 456',
    names: { ukr: 'Уганда', rus: 'Уганда', eng: 'Uganda', pol: 'Uganda' },
  },
  ZM: {
    dial: '+260',
    masks: ['XXX XXX XXX'],
    example: '955 123 456',
    names: { ukr: 'Замбія', rus: 'Замбия', eng: 'Zambia', pol: 'Zambia' },
  },
  ZW: {
    dial: '+263',
    masks: ['XX XXX XXXX'],
    example: '71 123 4567',
    names: { ukr: 'Зімбабве', rus: 'Зимбабве', eng: 'Zimbabwe', pol: 'Zimbabwe' },
  },
  AI: {
    dial: '+1264',
    masks: ['XXX XXXX'],
    example: '264 1234',
    names: { ukr: 'Ангілья', rus: 'Ангилья', eng: 'Anguilla', pol: 'Anguilla' },
  },
  AG: {
    dial: '+1268',
    masks: ['XXX XXXX'],
    example: '268 1234',
    names: {
      ukr: 'Антигуа і Барбуда',
      rus: 'Антигуа и Барбуда',
      eng: 'Antigua and Barbuda',
      pol: 'Antigua i Barbuda',
    },
  },
  AW: {
    dial: '+297',
    masks: ['XXX XXXX'],
    example: '297 1234',
    names: { ukr: 'Аруба', rus: 'Аруба', eng: 'Aruba', pol: 'Aruba' },
  },
  BS: {
    dial: '+1242',
    masks: ['XXX XXXX'],
    example: '242 1234',
    names: { ukr: 'Багамські Острови', rus: 'Багамы', eng: 'Bahamas', pol: 'Bahamy' },
  },
  BB: {
    dial: '+1246',
    masks: ['XXX XXXX'],
    example: '246 1234',
    names: { ukr: 'Барбадос', rus: 'Барбадос', eng: 'Barbados', pol: 'Barbados' },
  },
  BZ: {
    dial: '+501',
    masks: ['XXX XXXX'],
    example: '501 1234',
    names: { ukr: 'Беліз', rus: 'Белиз', eng: 'Belize', pol: 'Belize' },
  },
  BM: {
    dial: '+1441',
    masks: ['XXX XXXX'],
    example: '441 1234',
    names: { ukr: 'Бермудські Острови', rus: 'Бермуды', eng: 'Bermuda', pol: 'Bermudy' },
  },
  VG: {
    dial: '+1284',
    masks: ['XXX XXXX'],
    example: '284 1234',
    names: {
      ukr: 'Британські Віргінські Острови',
      rus: 'Британские Виргинские острова',
      eng: 'British Virgin Islands',
      pol: 'Brytyjskie Wyspy Dziewicze',
    },
  },
  CA: {
    dial: '+1',
    masks: ['(XXX) XXX-XXXX'],
    example: '(604) 555-0199',
    names: { ukr: 'Канада', rus: 'Канада', eng: 'Canada', pol: 'Kanada' },
  },
  KY: {
    dial: '+1345',
    masks: ['XXX XXXX'],
    example: '345 1234',
    names: {
      ukr: 'Кайманові Острови',
      rus: 'Каймановы острова',
      eng: 'Cayman Islands',
      pol: 'Kajmany',
    },
  },
  CR: {
    dial: '+506',
    masks: ['XXXX XXXX'],
    example: '6123 4567',
    names: { ukr: 'Коста-Рика', rus: 'Коста-Рика', eng: 'Costa Rica', pol: 'Kostaryka' },
  },
  CU: {
    dial: '+53',
    masks: ['X XXX XXXX'],
    example: '5 123 4567',
    names: { ukr: 'Куба', rus: 'Куба', eng: 'Cuba', pol: 'Kuba' },
  },
  CW: {
    dial: '+5999',
    masks: ['XXX XXXX'],
    example: '999 1234',
    names: { ukr: 'Кюрасао', rus: 'Кюрасао', eng: 'Curaçao', pol: 'Curaçao' },
  },
  DM: {
    dial: '+1767',
    masks: ['XXX XXXX'],
    example: '767 1234',
    names: { ukr: 'Домініка', rus: 'Доминика', eng: 'Dominica', pol: 'Dominika' },
  },
  DO: {
    dial: '+1809',
    masks: ['(XXX) XXX-XXXX'],
    example: '(809) 123-4567',
    names: {
      ukr: 'Домініканська Республіка',
      rus: 'Доминиканская Республика',
      eng: 'Dominican Republic',
      pol: 'Dominikana',
    },
  },
  SV: {
    dial: '+503',
    masks: ['XXXX XXXX'],
    example: '7012 3456',
    names: { ukr: 'Сальвадор', rus: 'Сальвадор', eng: 'El Salvador', pol: 'Salwador' },
  },
  GD: {
    dial: '+1473',
    masks: ['XXX XXXX'],
    example: '473 1234',
    names: { ukr: 'Гренада', rus: 'Гренада', eng: 'Grenada', pol: 'Grenada' },
  },
  GP: {
    dial: '+590',
    masks: ['XXX XX XX XX'],
    example: '590 12 34 56',
    names: { ukr: 'Гваделупа', rus: 'Гваделупа', eng: 'Guadeloupe', pol: 'Gwadelupa' },
  },
  GT: {
    dial: '+502',
    masks: ['XXXX XXXX'],
    example: '5012 3456',
    names: { ukr: 'Гватемала', rus: 'Гватемала', eng: 'Guatemala', pol: 'Gwatemala' },
  },
  HT: {
    dial: '+509',
    masks: ['XXXX XXXX'],
    example: '509 1234',
    names: { ukr: 'Гаїті', rus: 'Гаити', eng: 'Haiti', pol: 'Haiti' },
  },
  HN: {
    dial: '+504',
    masks: ['XXXX XXXX'],
    example: '9123 4567',
    names: { ukr: 'Гондурас', rus: 'Гондурас', eng: 'Honduras', pol: 'Honduras' },
  },
  JM: {
    dial: '+1876',
    masks: ['XXX XXXX'],
    example: '876 1234',
    names: { ukr: 'Ямайка', rus: 'Ямайка', eng: 'Jamaica', pol: 'Jamajka' },
  },
  MQ: {
    dial: '+596',
    masks: ['XXX XX XX XX'],
    example: '596 12 34 56',
    names: { ukr: 'Мартиніка', rus: 'Мартиника', eng: 'Martinique', pol: 'Martynika' },
  },
  MX: {
    dial: '+52',
    masks: ['XX XXXX XXXX'],
    example: '55 1234 5678',
    names: { ukr: 'Мексика', rus: 'Мексика', eng: 'Mexico', pol: 'Meksyk' },
  },
  MS: {
    dial: '+1664',
    masks: ['XXX XXXX'],
    example: '664 1234',
    names: { ukr: 'Монтсеррат', rus: 'Монтсеррат', eng: 'Montserrat', pol: 'Montserrat' },
  },
  NI: {
    dial: '+505',
    masks: ['XXXX XXXX'],
    example: '8123 4567',
    names: { ukr: 'Нікарагуа', rus: 'Никарагуа', eng: 'Nicaragua', pol: 'Nikaragua' },
  },
  PA: {
    dial: '+507',
    masks: ['XXXX XXXX'],
    example: '6123 4567',
    names: { ukr: 'Панама', rus: 'Панама', eng: 'Panama', pol: 'Panama' },
  },
  PR: {
    dial: '+1787',
    masks: ['(XXX) XXX-XXXX'],
    example: '(787) 123-4567',
    names: { ukr: 'Пуерто-Рико', rus: 'Пуэрто-Рико', eng: 'Puerto Rico', pol: 'Portoryko' },
  },
  BL: {
    dial: '+590',
    masks: ['XXX XX XX XX'],
    example: '590 12 34 56',
    names: {
      ukr: 'Сен-Бартелемі',
      rus: 'Сен-Бартелеми',
      eng: 'Saint Barthélemy',
      pol: 'Saint-Barthélemy',
    },
  },
  KN: {
    dial: '+1869',
    masks: ['XXX XXXX'],
    example: '869 1234',
    names: {
      ukr: 'Сент-Кітс і Невіс',
      rus: 'Сент-Китс и Невис',
      eng: 'Saint Kitts and Nevis',
      pol: 'Saint Kitts i Nevis',
    },
  },
  LC: {
    dial: '+1758',
    masks: ['XXX XXXX'],
    example: '758 1234',
    names: { ukr: 'Сент-Люсія', rus: 'Сент-Люсия', eng: 'Saint Lucia', pol: 'Saint Lucia' },
  },
  MF: {
    dial: '+590',
    masks: ['XXX XX XX XX'],
    example: '590 12 34 56',
    names: {
      ukr: 'Сен-Мартен',
      rus: 'Сен-Мартен',
      eng: 'Saint Martin',
      pol: 'Saint-Martin',
    },
  },
  PM: {
    dial: '+508',
    masks: ['XXX XXXX'],
    example: '508 1234',
    names: {
      ukr: "Сен-П'єр і Мікелон",
      rus: 'Сен-Пьер и Микелон',
      eng: 'Saint Pierre and Miquelon',
      pol: 'Saint-Pierre i Miquelon',
    },
  },
  VC: {
    dial: '+1784',
    masks: ['XXX XXXX'],
    example: '784 1234',
    names: {
      ukr: 'Сент-Вінсент і Гренадини',
      rus: 'Сент-Винсент и Гренадины',
      eng: 'Saint Vincent and the Grenadines',
      pol: 'Saint Vincent i Grenadyny',
    },
  },
  SX: {
    dial: '+1721',
    masks: ['XXX XXXX'],
    example: '721 1234',
    names: {
      ukr: 'Сінт-Мартен',
      rus: 'Синт-Мартен',
      eng: 'Sint Maarten',
      pol: 'Sint Maarten',
    },
  },
  TT: {
    dial: '+1868',
    masks: ['XXX XXXX'],
    example: '868 1234',
    names: {
      ukr: 'Тринідад і Тобаго',
      rus: 'Тринидад и Тобаго',
      eng: 'Trinidad and Tobago',
      pol: 'Trynidad i Tobago',
    },
  },
  TC: {
    dial: '+1649',
    masks: ['XXX XXXX'],
    example: '649 1234',
    names: {
      ukr: 'Теркс і Кайкос',
      rus: 'Теркс и Кайкос',
      eng: 'Turks and Caicos Islands',
      pol: 'Turks i Caicos',
    },
  },
  US: {
    dial: '+1',
    masks: ['(XXX) XXX-XXXX'],
    example: '(415) 555-0132',
    names: { ukr: 'США', rus: 'США', eng: 'United States', pol: 'Stany Zjednoczone' },
  },
  VI: {
    dial: '+1340',
    masks: ['XXX XXXX'],
    example: '340 1234',
    names: {
      ukr: 'Віргінські Острови США',
      rus: 'Виргинские острова США',
      eng: 'U.S. Virgin Islands',
      pol: 'Wyspy Dziewicze Stanów Zjednoczonych',
    },
  },
  AR: {
    dial: '+54',
    masks: ['XXX XXX XXXX'],
    example: '11 1234 5678',
    names: { ukr: 'Аргентина', rus: 'Аргентина', eng: 'Argentina', pol: 'Argentyna' },
  },
  BO: {
    dial: '+591',
    masks: ['XXXX XXXX'],
    example: '7123 4567',
    names: { ukr: 'Болівія', rus: 'Боливия', eng: 'Bolivia', pol: 'Boliwia' },
  },
  BR: {
    dial: '+55',
    masks: ['XX XXXXX XXXX'],
    example: '11 91234 5678',
    names: { ukr: 'Бразилія', rus: 'Бразилия', eng: 'Brazil', pol: 'Brazylia' },
  },
  CL: {
    dial: '+56',
    masks: ['X XXXX XXXX'],
    example: '9 1234 5678',
    names: { ukr: 'Чилі', rus: 'Чили', eng: 'Chile', pol: 'Chile' },
  },
  CO: {
    dial: '+57',
    masks: ['XXX XXX XXXX'],
    example: '300 123 4567',
    names: { ukr: 'Колумбія', rus: 'Колумбия', eng: 'Colombia', pol: 'Kolumbia' },
  },
  EC: {
    dial: '+593',
    masks: ['XX XXX XXXX'],
    example: '99 123 4567',
    names: { ukr: 'Еквадор', rus: 'Эквадор', eng: 'Ecuador', pol: 'Ekwador' },
  },
  FK: {
    dial: '+500',
    masks: ['XXXXX'],
    example: '12345',
    names: {
      ukr: 'Фолклендські Острови',
      rus: 'Фолклендские острова',
      eng: 'Falkland Islands',
      pol: 'Falklandy',
    },
  },
  GF: {
    dial: '+594',
    masks: ['XXX XX XX XX'],
    example: '594 12 34 56',
    names: {
      ukr: 'Французька Гвіана',
      rus: 'Французская Гвиана',
      eng: 'French Guiana',
      pol: 'Gujana Francuska',
    },
  },
  GY: {
    dial: '+592',
    masks: ['XXX XXXX'],
    example: '592 1234',
    names: { ukr: 'Гайана', rus: 'Гайана', eng: 'Guyana', pol: 'Gujana' },
  },
  PY: {
    dial: '+595',
    masks: ['XXX XXX XXX'],
    example: '981 123 456',
    names: { ukr: 'Парагвай', rus: 'Парагвай', eng: 'Paraguay', pol: 'Paragwaj' },
  },
  PE: {
    dial: '+51',
    masks: ['XXX XXX XXX'],
    example: '912 345 678',
    names: { ukr: 'Перу', rus: 'Перу', eng: 'Peru', pol: 'Peru' },
  },
  SR: {
    dial: '+597',
    masks: ['XXX XXXX'],
    example: '597 1234',
    names: { ukr: 'Суринам', rus: 'Суринам', eng: 'Suriname', pol: 'Surinam' },
  },
  UY: {
    dial: '+598',
    masks: ['XXXX XXXX'],
    example: '9123 4567',
    names: { ukr: 'Уругвай', rus: 'Уругвай', eng: 'Uruguay', pol: 'Urugwaj' },
  },
  VE: {
    dial: '+58',
    masks: ['XXX XXX XXXX'],
    example: '412 123 4567',
    names: { ukr: 'Венесуела', rus: 'Венесуэла', eng: 'Venezuela', pol: 'Wenezuela' },
  },
  AU: {
    dial: '+61',
    masks: ['XXX XXX XXX'],
    example: '412 345 678',
    names: { ukr: 'Австралія', rus: 'Австралия', eng: 'Australia', pol: 'Australia' },
  },
  CK: {
    dial: '+682',
    masks: ['XXXXX'],
    example: '12345',
    names: {
      ukr: 'Острови Кука',
      rus: 'Острова Кука',
      eng: 'Cook Islands',
      pol: 'Wyspy Cooka',
    },
  },
  FJ: {
    dial: '+679',
    masks: ['XXX XXXX'],
    example: '701 2345',
    names: { ukr: 'Фіджі', rus: 'Фиджи', eng: 'Fiji', pol: 'Fidżi' },
  },
  PF: {
    dial: '+689',
    masks: ['XX XX XX XX'],
    example: '89 12 34 56',
    names: {
      ukr: 'Французька Полінезія',
      rus: 'Французская Полинезия',
      eng: 'French Polynesia',
      pol: 'Polinezja Francuska',
    },
  },
  GU: {
    dial: '+1671',
    masks: ['XXX XXXX'],
    example: '671 1234',
    names: { ukr: 'Гуам', rus: 'Гуам', eng: 'Guam', pol: 'Guam' },
  },
  KI: {
    dial: '+686',
    masks: ['XXXXXX'],
    example: '650123',
    names: { ukr: 'Кірибаті', rus: 'Кирибати', eng: 'Kiribati', pol: 'Kiribati' },
  },
  MH: {
    dial: '+692',
    masks: ['XXX XXXX'],
    example: '235 1234',
    names: {
      ukr: 'Маршаллові Острови',
      rus: 'Маршалловы острова',
      eng: 'Marshall Islands',
      pol: 'Wyspy Marshalla',
    },
  },
  FM: {
    dial: '+691',
    masks: ['XXX XXXX'],
    example: '350 1234',
    names: { ukr: 'Мікронезія', rus: 'Микронезия', eng: 'Micronesia', pol: 'Mikronezja' },
  },
  NR: {
    dial: '+674',
    masks: ['XXX XXX'],
    example: '555 123',
    names: { ukr: 'Науру', rus: 'Науру', eng: 'Nauru', pol: 'Nauru' },
  },
  NC: {
    dial: '+687',
    masks: ['XX XX XX'],
    example: '87 12 34',
    names: {
      ukr: 'Нова Каледонія',
      rus: 'Новая Каледония',
      eng: 'New Caledonia',
      pol: 'Nowa Kaledonia',
    },
  },
  NZ: {
    dial: '+64',
    masks: ['XXX XXX XXXX'],
    example: '21 123 4567',
    names: {
      ukr: 'Нова Зеландія',
      rus: 'Новая Зеландия',
      eng: 'New Zealand',
      pol: 'Nowa Zelandia',
    },
  },
  NU: {
    dial: '+683',
    masks: ['XXXX'],
    example: '1234',
    names: { ukr: 'Ніуе', rus: 'Ниуэ', eng: 'Niue', pol: 'Niue' },
  },
  NF: {
    dial: '+6723',
    masks: ['XXXXX'],
    example: '12345',
    names: {
      ukr: 'Острів Норфолк',
      rus: 'Остров Норфолк',
      eng: 'Norfolk Island',
      pol: 'Wyspa Norfolk',
    },
  },
  MP: {
    dial: '+1670',
    masks: ['XXX XXXX'],
    example: '670 1234',
    names: {
      ukr: 'Північні Маріанські Острови',
      rus: 'Северные Марианские острова',
      eng: 'Northern Mariana Islands',
      pol: 'Mariany Północne',
    },
  },
  PW: {
    dial: '+680',
    masks: ['XXX XXXX'],
    example: '488 1234',
    names: { ukr: 'Палау', rus: 'Палау', eng: 'Palau', pol: 'Palau' },
  },
  PG: {
    dial: '+675',
    masks: ['XXX XXXX'],
    example: '7012 3456',
    names: {
      ukr: 'Папуа Нова Гвінея',
      rus: 'Папуа Новая Гвинея',
      eng: 'Papua New Guinea',
      pol: 'Papua-Nowa Gwinea',
    },
  },
  WS: {
    dial: '+685',
    masks: ['XXXX XXX'],
    example: '601 234',
    names: { ukr: 'Самоа', rus: 'Самоа', eng: 'Samoa', pol: 'Samoa' },
  },
  SB: {
    dial: '+677',
    masks: ['XXXXX'],
    example: '74234',
    names: {
      ukr: 'Соломонові Острови',
      rus: 'Соломоновы острова',
      eng: 'Solomon Islands',
      pol: 'Wyspy Salomona',
    },
  },
  TK: {
    dial: '+690',
    masks: ['XXXX'],
    example: '1234',
    names: { ukr: 'Токелау', rus: 'Токелау', eng: 'Tokelau', pol: 'Tokelau' },
  },
  TO: {
    dial: '+676',
    masks: ['XXXXX'],
    example: '77123',
    names: { ukr: 'Тонга', rus: 'Тонга', eng: 'Tonga', pol: 'Tonga' },
  },
  TV: {
    dial: '+688',
    masks: ['XXXXXX'],
    example: '901234',
    names: { ukr: 'Тувалу', rus: 'Тувалу', eng: 'Tuvalu', pol: 'Tuvalu' },
  },
  VU: {
    dial: '+678',
    masks: ['XXXXX'],
    example: '59123',
    names: { ukr: 'Вануату', rus: 'Вануату', eng: 'Vanuatu', pol: 'Vanuatu' },
  },
  WF: {
    dial: '+681',
    masks: ['XX XX XX'],
    example: '81 12 34',
    names: {
      ukr: 'Уолліс і Футуна',
      rus: 'Уоллис и Футуна',
      eng: 'Wallis and Futuna',
      pol: 'Wallis i Futuna',
    },
  },
};

export function getCountry(iso2: string, lang: keyof CountryNames = 'ukr'): Country | null {
  const entry = COUNTRIES[iso2];
  if (!entry) return null;
  return { iso2, name: entry.names[lang] || entry.names.ukr, ...entry };
}

export function listCountries(lang: keyof CountryNames = 'ukr'): Country[] {
  return Object.entries(COUNTRIES).map(([iso2, entry]) => ({
    iso2,
    name: entry.names[lang] || entry.names.ukr,
    ...entry,
  }));
}
